package rbt.cagamas.mortgagecalculation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Mortgage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Mortgage Amount")
   private java.lang.Integer mortgageAmount;

   @org.kie.api.definition.type.Label("No of years")
   private java.lang.Integer noOfYears;

   @org.kie.api.definition.type.Label("Interest Rate")
   private Float interestRate;

   @org.kie.api.definition.type.Label("Product Type")
   private java.lang.String productType;

   @org.kie.api.definition.type.Label("Product")
   private java.lang.String product;

   @org.kie.api.definition.type.Label("Validation Errors")
   private rbt.cagamas.mortgagecalculation.ValidationError validationErrors;

   @org.kie.api.definition.type.Label(value = "Verify Status")
   private java.lang.Boolean verifyStatus;

   @org.kie.api.definition.type.Label(value = "Approve Status")
   private java.lang.Boolean approveStatus;

   public Mortgage()
   {
   }

   public java.lang.Integer getMortgageAmount()
   {
      return this.mortgageAmount;
   }

   public void setMortgageAmount(java.lang.Integer mortgageAmount)
   {
      this.mortgageAmount = mortgageAmount;
   }

   public java.lang.Integer getNoOfYears()
   {
      return this.noOfYears;
   }

   public void setNoOfYears(java.lang.Integer noOfYears)
   {
      this.noOfYears = noOfYears;
   }

   public java.lang.String getProductType()
   {
      return this.productType;
   }

   public void setProductType(java.lang.String productType)
   {
      this.productType = productType;
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public rbt.cagamas.mortgagecalculation.ValidationError getValidationErrors()
   {
      return this.validationErrors;
   }

   public void setValidationErrors(
         rbt.cagamas.mortgagecalculation.ValidationError validationErrors)
   {
      this.validationErrors = validationErrors;
   }

   public java.lang.Float getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Float interestRate)
   {
      this.interestRate = interestRate;
   }

   public java.lang.Boolean getVerifyStatus()
   {
      return this.verifyStatus;
   }

   public void setVerifyStatus(java.lang.Boolean verifyStatus)
   {
      this.verifyStatus = verifyStatus;
   }

   public java.lang.Boolean getApproveStatus()
   {
      return this.approveStatus;
   }

   public void setApproveStatus(java.lang.Boolean approveStatus)
   {
      this.approveStatus = approveStatus;
   }

   public Mortgage(java.lang.Integer mortgageAmount, java.lang.Integer noOfYears,
         java.lang.Float interestRate, java.lang.String productType,
         java.lang.String product,
         rbt.cagamas.mortgagecalculation.ValidationError validationErrors,
         java.lang.Boolean verifyStatus, java.lang.Boolean approveStatus)
   {
      this.mortgageAmount = mortgageAmount;
      this.noOfYears = noOfYears;
      this.interestRate = interestRate;
      this.productType = productType;
      this.product = product;
      this.validationErrors = validationErrors;
      this.verifyStatus = verifyStatus;
      this.approveStatus = approveStatus;
   }

}